// Inlines Leaflet into the app bundle so the map shell works without a network connection.
// Run after upgrading the `leaflet` dev dependency: npm run vendor:leaflet
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const root = dirname(require.resolve('leaflet/package.json'));
const js = readFileSync(join(root, 'dist/leaflet.js'), 'utf8');
const css = readFileSync(join(root, 'dist/leaflet.css'), 'utf8');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

mkdirSync('src/vendor', { recursive: true });
writeFileSync('src/vendor/leaflet.ts',
  `// Generated by scripts/vendor-leaflet.mjs from leaflet@${version} (BSD-2-Clause). Do not edit.\n` +
  `export const LEAFLET_JS = ${JSON.stringify(js)};\nexport const LEAFLET_CSS = ${JSON.stringify(css)};\n`);
console.log(`Vendored leaflet@${version}`);
